from os import name
from . import views
from django.urls import path , include

app_name = 'main'

urlpatterns = [
    path('',views.dashboard, name='dashboard'),
    path('blog1',views.blog1, name='blog1'),
    path('blog2',views.blog2, name='blog2'),
    path('blogcard',views.blogcard, name='blogcard'),
    path('blogsingle1',views.blogsingle1, name='blogsingle1'),
    path('blogsingle',views.blogsingle, name='blogsingle'),
    path('bookdescription',views.bookdescription, name='bookdescription'),
    path('book',views.book, name='book'),
    path('colors',views.colors, name='colors'),
    path('coursecard',views.coursecard, name='coursecard'),
    path('courseintro',views.courseintro, name='courseintro'),
    path('courselist',views.courselist, name='courselist'),
    path('coursepathlevel',views.coursepathlevel, name='coursepathlevel'),
    path('coursepath',views.coursepath, name='coursepath'),
    path('courseresume',views.courseresume, name='courseresume'),
    path('courses',views.courses, name='courses'),
    path('cover',views.cover, name='cover'),
    path('developmentelements',views.developmentelements, name='developmentelements'),
    path('developmenticons',views.developmenticons, name='developmenticons'),
    path('dropdown',views.dropdown, name='dropdown'),
    path('elementsgrid',views.elementsgrid, name='elementsgrid'),
    path('flex',views.flex, name='flex'),
    path('formlogin',views.formlogin, name='formlogin'),
    path('formmordernlogin',views.formmodernlogin, name='formmordernlogin'),
    path('grid',views.grid, name='grid'),
    path('home',views.home, name='home'),
    path('inverse',views.inverse, name='inverse'),
    path('index',views.index,name='index'),
    path('pagecomponents',views.pagecomponents, name='pagecomponents'),
    path('pagecontact',views.pagecontact, name='pagecontact'),
    path('pageelements',views.pageelements, name='pageelements'),
    path('pageicons',views.pageicons, name='pageicons'),
    path('pagelogin',views.pagelogin, name='pagelogin'),
    path('pagepricing',views.pagepricing, name='pagepricing'),
    path('pagePrivacy',views.pageprivacy, name='pagePrivacy'),
    path('pageprivecy',views.pageprivecy, name='pageprivecy'),
    path('pageregister',views.pageregister, name='pageregister'),
    path('pagesimplelogin',views.pagesimplelogin, name='pagesimplelogin'),
    path('pagesimpleregister',views.pagesimpleregister, name='pagesimpleregister'),
    path('pageterm',views.pageterm, name='pageterm'),
    path('pagesterms',views.pagesterms, name='pagesterms'),
    path('profile1',views.profile1, name='profile1'),
    path('profileedit',views.profileedit, name='profileedit'),
    path('slider',views.slider, name='slider'),
    path('slideshow',views.slideshow, name='slideshow'),
    path('specialitycommingsoon',views.specialitycommingsoon, name='specialitycommingsoon'),
    path('tabs',views.tabs, name='tabs'),
    path('takecourse',views.takecourse, name='takecourse'),
    path('transition',views.transition, name='transition'),
    path('userprofile1',views.userprofile1, name='userprofile1'),
    path('userprofileedit',views.userprofileedit, name='userprofileedit'),
    path('userprofile',views.userprofile, name='userprofile'),
    path('utility',views.utility, name='utility'),
]

